<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ManageUsers.aspx.cs" Inherits="LTWebForm.Account.ManageUsers" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">


    <title>Edit,update and delete User accounts in asp.net membership</title>
    <style type="text/css">
        .GridviewDiv {
            font-size: 100%;
            font-family: 'Lucida Grande', 'Lucida Sans Unicode', Verdana, Arial, Helevetica, sans-serif;
            color: #303933;
        }

        Table.Gridview {
            border: solid 1px #df5015;
        }

        .Gridview th {
            color: #FFFFFF;
            border-right-color: #abb079;
            border-bottom-color: #abb079;
            padding: 0.5em 0.5em 0.5em 0.5em;
            text-align: center
        }

        .Gridview td {
            border-bottom-color: #f0f2da;
            border-right-color: #f0f2da;
            padding: 0.5em 0.5em 0.5em 0.5em;
        }

        .Gridview tr {
            color: Black;
            background-color: White;
            text-align: left
        }

        :link, :visited {
            color: #DF4F13;
            text-decoration: none
        }
    </style>

    <div class="GridviewDiv">
        <asp:GridView ID="gvDetails" runat="server" CssClass="Gridview" AutoGenerateColumns="false"
            AutoGenerateDeleteButton="true" AutoGenerateEditButton="true"
            OnRowCancelingEdit="gvDetails_RowCancelingEdit"
            OnRowDeleting="gvDetails_RowDeleting" OnRowEditing="gvDetails_RowEditing"
            OnRowUpdating="gvDetails_RowUpdating">
            <HeaderStyle BackColor="#df5015" />
            <Columns>
                <asp:BoundField DataField="UserName" HeaderText="UserName" ReadOnly="true" />
                <asp:BoundField DataField="Email" HeaderText="Email" />
            </Columns>
        </asp:GridView>
        <asp:Label ID="lblResult" runat="server" Font-Bold="true" />
    </div>

</asp:Content>
