<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Role.aspx.cs" Inherits="LTWebForm.Account.Role" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <title>Create and Delete Roles in asp.net Membership</title>
    <style type="text/css">
        .GridviewDiv {
            font-size: 100%;
            font-family: 'Lucida Grande', 'Lucida Sans Unicode', Verdana, Arial, Helevetica, sans-serif;
            color: #303933;
        }

        Table.Gridview {
            border: solid 1px #df5015;
        }

        .Gridview th {
            color: #FFFFFF;
            border-right-color: #abb079;
            border-bottom-color: #abb079;
            padding: 0.5em 0.5em 0.5em 0.5em;
            text-align: center
        }

        .Gridview td {
            border-bottom-color: #f0f2da;
            border-right-color: #f0f2da;
            padding: 0.5em 0.5em 0.5em 0.5em;
        }

        .Gridview tr {
            color: Black;
            background-color: White;
            text-align: left
        }

        :link, :visited {
            color: #DF4F13;
            text-decoration: none
        }
    </style>

    <div class="GridviewDiv">
        <table align="center">
            <tr>
                <td><b>Enter RoleName:</b> </td>
                <td>
                    <asp:TextBox ID="txtRole" runat="server" /></td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <asp:Button ID="btnCreate" runat="server" Text="Create Role" OnClick="btnCreate_Click" /></td>
            </tr>
            <tr>
                <td colspan="2">
                    <asp:Label ID="lblResult" runat="server" Font-Bold="true" /></td>
            </tr>
            <tr>
                <td colspan="2">
                    <asp:GridView ID="gvRoles" runat="server" CssClass="Gridview" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" OnRowDeleting="gvRoles_RowDeleting">
                        <HeaderStyle BackColor="#df5015" />
                        <Columns>
                            <asp:TemplateField HeaderText="Role Name">
                                <ItemTemplate>
                                    <asp:Label ID="lblRole" runat="server" Text='<%#Container.DataItem %>' />
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                    </asp:GridView>
                </td>
            </tr>
        </table>
    </div>
</asp:Content>
